// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM_yImFIJwhIqgK108KpQxT5Sal-1TmC0',
    appId: '1:1081245700531:web:f4d4b0b21f855c93b0fbc6',
    messagingSenderId: '1081245700531',
    projectId: 'not-so-secret-e7acd',
    authDomain: 'not-so-secret-e7acd.firebaseapp.com',
    storageBucket: 'not-so-secret-e7acd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-H3C4TYjuJ9A53KuaamMWdU17n5OPdUI',
    appId: '1:1081245700531:android:e9669c06093c5d96b0fbc6',
    messagingSenderId: '1081245700531',
    projectId: 'not-so-secret-e7acd',
    storageBucket: 'not-so-secret-e7acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjKZ0pvZydjOr4yhuV3NYslxGjNc7lVa8',
    appId: '1:1081245700531:ios:09e2d5fdc8f9be4fb0fbc6',
    messagingSenderId: '1081245700531',
    projectId: 'not-so-secret-e7acd',
    storageBucket: 'not-so-secret-e7acd.appspot.com',
    androidClientId: '1081245700531-24k4ge536t1s91ol124asumaivi07fr4.apps.googleusercontent.com',
    iosClientId: '1081245700531-q46mj403755j5daphq2c4ovossdfsnh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notSoSecret',
  );
}
